### PR TITLE
Added support to Gnome 3.24 and 3.26

### LINKED ISSUE #202: Add Support for Gnome 3.26
Please add support for Gnome 3.26

### PR DESCRIPTION
**Pull request by e-minguez**
Fixes #202

### CODE REVIEW

**Comment by zzrough** [comment]
It's weird versions are not checked anymore since gnome-shell 3.24? This should not be needed. Which Linux distribution are you using?

Do you have the /org/gnome/shell/disable-extension-version-validation set or unset? This setting should automatically be enabled since 3.24 (or 3.22 I do not remember).

**Comment by e-minguez** [comment]
I'm using Fedora 27 freshly installed and it seems the validation is enabled by default:

```
$ gsettings get org.gnome.shell disable-extension-version-validation
true
```

**Comment by zzrough** [comment]
true means the setting is on which means validation is disabled (see the key name).

As you are now you do not need this change. Did you have any problem or this was more to fix it because you thought it was an error?

We should not need this anymore.

Le 28 décembre 2017 15:12:44 GMT+01:00, "Eduardo Mínguez" <notifications@github.com> a écrit :
>I'm using Fedora 27 freshly installed and it seems the validation is
>enabled by default:
>
>```
>$ gsettings get org.gnome.shell disable-extension-version-validation
>true
>```
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/zzrough/gs-extensions-drop-down-terminal/pull/204#issuecomment-354294356

--S

**Comment by e-minguez** [comment]
Actually it happened to me because I'm using [this script](https://github.com/NicolasBernaerts/ubuntu-scripts/blob/master/ubuntugnome/gnomeshell-extension-manage) to install all my extension via cli.
I think it won't hurt to add the versions it supports, but feel free to close it if you think it is not needed.
Thanks!

**Comment by erkinalp** [comment]
Same for 3.28.

**Pull request closed without merging**
