### PR TITLE
Fix and improve transparency

### PR DESCRIPTION
**Pull request by letorbi**
Hi,

this pull request fixes an issue I faced when using the drop down terminal with GNOME 3.20 (Arch Linux): The lastest official version does not ensure that the window, in which the terminal widget is placed, is transparent. This might break transparency (as in my case), since even though the transparency of the terminal itself is working, the current desktop would be hidden by the non-transarent window. Commit c4621fe fixes this by forcing the window background colour to be transparent when transparency is used.

Apart from that the current implementation seems to use opacity instead of the alpha value of the terminal background. This causes the terminal text to be almost invisible when using low values for transparency. Commit c4621fe improves this behaviour by applying the transparency value only to the alpha channel of the terminal background and the scrollbar. This way the terminal text is visible even with full transparency.

Bai
Torben

### CODE REVIEW

**Comment by smurfendrek123** [comment]
Thank you so much for fixing this, i hope it gets patched in soon!

**Comment by letorbi** [comment]
Yeah, I hope it gets merged soon, too. I really wonder why it hasn't been merged yet and would love to hear from @zzrough about that...

**Comment by romgrk** [comment]
#151 is better I think.

Readings:
https://bugzilla.gnome.org/show_bug.cgi?id=765433#c1 (bugtracker, boring)
https://blogs.gnome.org/mclasen/2016/04/29/yet-another-gtk-update/ (good résumé of whats going on)
https://blogs.gnome.org/mortenw/2016/05/06/change/ (this one is less relevant but very funny)

**Comment by letorbi** [comment]
Agree, please merge #151 instead of this one.

**Comment by zzrough** [comment]
@letorbi @romgrk  Sorry for the huge lag, I'm merging #151 and #152 thanks for the PRs guys

**Pull request closed without merging**
