### PR TITLE
Update for 3.30

### PR DESCRIPTION
**Pull request by anarchodin**
Changes in GNOME need a search-and-replace approach. This should work 
for both the new version and prior versions.

### CODE REVIEW

**Comment by anarchodin** [comment]
Should solve #217.

**Comment by frol** [comment]
It works for me!

@anarchodin Thank you!

**Comment by ohadeytan** [comment]
Works here too (on Arch)

Thanks!

**Comment by zzrough** [comment]
great, thanks! just a missing semicolon that I'll fix in an upcoming commit

**Comment by victorsosa** [comment]
those the file https://github.com/zzrough/gs-extensions-drop-down-terminal/blob/master/drop-down-terminal%40gs-extensions.zzrough.org/metadata.json has to be updated too?

**Comment by soloturn** [comment]
@anarchodin mind releasing a verison again?

**Comment by zzrough** [comment]
@victorsosa the version information is not used since 3.24. It's driven by the /org/gnome/shell/disable-extension-version-validation dconf key, but all distros let it on by deault.

**Comment by zzrough** [comment]
@soloturn thanks for the reminder, I thought I released it when I merged the 3.30 I've added the version for review. It should be ok in the next 24h hopefully.

**Comment by victorsosa** [comment]
@zzrough still it is not working; I just updated the plug-in

**Comment by victorsosa** [comment]
Ok I got the error log: 
TypeError: Global.screen is undefined

**Comment by victorsosa** [comment]
Found the issue; you should check undefined in this way:
typeof global.screen === "undefined"

I will send a PR with the change

**Comment by frol** [comment]
@victorsosa This is really odd. The extension works fine with just this patch and my JS knowledge makes me believe that this fix is completely fine (JS won't raise an exception if you access a non-existing (undefined) attribute of an object). Thus, I believe that your patch is unnecessary.

**Comment by erkinalp** [comment]
@frol GNOME extension system crashes as a whole if you reference an undefined.

**Comment by frol** [comment]
@erkinalp This is true only if you reference a variable that is not defined (i.e. undefined), but it won't crash if you access a non-existing attribute of a defined object:

```javascript
let x = undefined_variable;  // <--- crash

let a = {};
let b = a.undefined_attribute;  // `b` will be silently defined with `undefined` value and won't crash
```

**Comment by anarchodin** [comment]
[The spec](https://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-get-p-receiver) says an object access should return `undefined` if the key doesn't exist. It appears the `global` object can _technically_ have a different getter, but that doesn't seem to be the case here and would in any case be a little perplexing.

The error described by @victorsosa seems to be the original one - i.e., accessing a property of `global.screen` without checking that it is defined first. Maybe the upgrade took a bit longer than expected to propagate?

**Pull request merged**
