### PR TITLE
#14 Tabs support

### PR DESCRIPTION
**Pull request by bigbn**

### CODE REVIEW

**Comment by zzrough** [comment]
Sorry, I did not have time to look into this. I'm really interested as this is one of the most requested thing.

**Comment by igorbarkowsky** [comment]
@bigbn try [this](https://github.com/bigbn/gs-extensions-drop-down-terminal), works well. Use your version since today.

@zzrough, recommend you test @bigbn version. Its fast and looks clean.

**Comment by zzrough** [comment]
@igorbarkowsky I never had the chance to look at the code. I still use this project all the time but I did not have any time except small merges here and there for the past two gnome releases. I hope to get some time by april.

**Comment by razvanc-r** [comment]
I would like to throw my voice around, I'm against tabs :)

**Comment by kitingChris** [comment]
@razvanc-r why not adding it as optional feature that can get disabled. Many of us would love to see it cause it actually would help us to work more effective. No one wants it as mandatory feature. Just as an optional.

**Comment by kitingChris** [comment]
@zzrough I checked @bigbn version out and it works very well! 
Perhaps @bigbn you could resolve the conflicts and make tabs support on default off then maybe everyone can be happy :)

**Comment by zzrough** [comment]
I'd very much love too, I have almost no free time at all. I'll get back
to it, I simply do not know when.

**Comment by razvanc-r** [comment]
@kitingChris it's fine I can imagine it would be helpful for a lot of GUI-oriented people, I just got too used to tmux and other tools to see the benefit of this feature :)

**Comment by bigbn** [comment]
Conflicts resolved, and tabs disabled by default

**Comment by yeralin** [comment]
@bigbn Love your fork. One request tho (if it is easy to implement), switch between tabs with <key>+<num> like "CTRL+2" to switch to second tab like in iTerm.

**Comment by zzrough** [comment]
@bigbn Wow, you did such an awesome work! So many fixes and improvements over this PR... I'm sorry I totally failed to merge this and maintain this software correctly. I've created a startup and have been drown into it days and nights for the past 4y.

Do you want access to this  repositories to maintain it properly? I just looked at it quickly but I suppose if I merge and revert the rfc for new ext id and dbus path I can merge and release it as-is?

I'm not too fond of the rpc JS-Standard though, i'd rather stick to the upstream gnome-shell coding way. At least the semi-colon removal at end of the lines seems weird to me. If you'd rather keep it I see no objection though. You're maintaining the project way better than me :)

**Comment by bigbn** [comment]
> Just another question, is reseting the whole terminal by design or a slight bug? If I use ctrl-D it closes all the tabs, I'd expect it would close only the current tab.

It's some kind of bug, not regular. Looks like it depends on distro configuration. 
I get it in on my home desktop, but I also have normal behavior on office computer. I know how to fix it, but I can't find the reason.

**Comment by bigbn** [comment]
I think, better I'll  focus only on my fork. It is complicated project for a one person and I'm not ready to support all of its features.

**Pull request closed without merging**
