### PR TITLE
Add terminal positioning, left, top, right, bottom.

### PR DESCRIPTION
**Pull request by TonicArtos**
- Add terminal position combobox to prefs UI.
- Add gschema enum key for terminal position.
- Layout terminal according to position selected.
- Compile new gschema.
- Update animation direction for position.
- Clip terminal to screen rather than changing animation style.

---
Caveats:
Dynamic update for position changes is buggy. Switching from left or right to bottom results in top, but toggling fixes. Switching from top and bottom to right results in left, but toggling fixes. This seems to be some strange interaction with SetGeometry, but I haven't been able to yet figure it out.

### CODE REVIEW

**Comment by zzrough** [comment]
Wow crap, I've completely slept through this pull request. I'm sorry. Thanks a lot for contributing. I'll try the patch and see if I can fix the caveats.

**Comment by TonicArtos** [comment]
Hi @zzrough, are you still interested in this patch? Is there anything I can do to help get this merged?

**Comment by zara86** [comment]
I tried on Arch + Gnome 3.18.x and...wow, it's awesome!

**Comment by zzrough** [comment]
Still very busy and still very interested. Wednesday is a holiday here, I'll try to look into the PR and fix the caveats.

**Comment by TonicArtos** [comment]
Okay, so the problem seems to be related to the window type hint set in terminal.js. Changing it from DROPDOWN_MENU to DOCK works as a fix. From what I've read DOCK is more appropriate for this utility too. The window manager is supposed to wholly honour the size and position of the window if it is a dock type. The user is not supposed to be able to directly move and resize dock windows either.

**Comment by TonicArtos** [comment]
Ah, it seems things have diverged more than I realised. Also, the dock change already happened. My bad. Tomorrow I will bring my branch up to date and start a new pull request. That should make things easier for you.

**Comment by zzrough** [comment]
On 3.18, we have switched to COMBO, See #118 Many thanks for your work. Historically, the window input type effect on Mutter positionning changed quite much version after version. At the start only DROPDOWN_MENU did not have any drawback. I hope COMBO does not break your stuff too much.

**Comment by zara86** [comment]
I can say no to that: I've tested with "COMBO" and it's work.

**Pull request closed without merging**
