### PR TITLE
Add position configuration

### PR DESCRIPTION
**Pull request by TonicArtos**
This pull request is to add position configuration. Implementing this properly required changing the window type to DOCK and implementing methods to focus the window. Mouse and keyboard (shortcut) focus switching is supported.

### CODE REVIEW

**Comment by zzrough** [comment]
Wow, thanks for the PR, that's an amazing patch! I've tested on a single and multi-monitor setup and everything works fine. Even the clipping is such a better solution than mine scaling the actor as a hack. I just found a typo in the configuration panel and that's all.

I just have a question regarding the focus on enter_notify_event. Did you do that on purpose in order not to click? I always preferred to click to have the focus back as sometimes I move my mouse and the terminal gets the focus. Having click-to-focus is okay for you or you changed it because DOCK was getting in the way of focus handling or because you wanted the focus-on-hover ?

I've locally changed it back to focus, but everything else is perfect.

**Comment by TonicArtos** [comment]
Yes, I was having problems with DOCK and focus, but I thought that having DOCK and implementing focus for mouse and keyboard was better than the alternatives. I did try implementing click-to-focus in addition to focus-on-hover. However, I was unable to get click-to-focus to work as for some reason I was not receiving button1 (left) and button3 (right) events from the window. I planned on hooking it up with the dconf key for mutters mouse focus configuration too. Anwyay, I reasoned you might know what is going on there with the button events so I just went ahead with this pull request for now.

**Comment by TonicArtos** [comment]
I just had a thought and looked at terminal.js again. Perhaps 
```js
terminal.connect("button_release_event",  Lang.bind(this, this._terminalButtonReleased));
```
is the cause of this. I'll check.

**Comment by TonicArtos** [comment]
Yes! okay, that was the cause of the problem. The event was being swallowed by the function bound to `"button_release_event"`. So, I can implement both click-to-focus and hover-to-focus and switch depending on the mutter configuration, and default to click-to-focus if the configuration is missing. Is this fine?

**Comment by TonicArtos** [comment]
Okay, I decided to do it anyway.

---
9d03473
*Enhance focus behaviour.*
- Add click-to-focus.
- Add function to convenience.js to safely fetch installed gio.settings.
- Observe and obey org.gnome.desktop.wm.preferences.focus-mode for mouse
  focus behaviour.

**Comment by zzrough** [comment]
Yep, that's how I restored click-to-focus locally, but your way of supporting the wm property is the good way to do it. Nice work again!

**Comment by zzrough** [comment]
I reviewed the code a bit and fixed the focus mode update (the updated variable was wrong). I just reverted to the regular keyboard focus, I find it weird to refocus using the toggling key. See the rationale in my commit. Or do you really need it? I could add a preference if needed...

Thanks again for the awesome work!

**Comment by zzrough** [comment]
Ho, I'll release in a few days, I prefer to play a lot with the terminal to see if I get regressions with day-to-day work.

**Comment by TonicArtos** [comment]
I checked a couple of your issues the other night and noted somebody had an issue with hidpi support. I turned on hidpi temporarily for my laptop and noticed some positioning and sizing issues with my branch.

**Comment by zzrough** [comment]
Mmh I quickly tried yesterday but keeping the top position. Indeed the window seems to come from the bottom from time to time, and with position set to "right", the size seems wrong.

**Comment by TonicArtos** [comment]
I'll see what I can do about it later in the week. Unfortunately, I have a
deadline elsewhere I have to meet before then.

**Comment by zzrough** [comment]
No pbm at all, especially when I myself got busy with life and you had to wait many months to get the PR reviewed :)

**Pull request merged**
